version: "3.8"

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb

  mainserver:
    build:
      context: ./idemainserver
      dockerfile: Dockerfile
    image: ${REGISTRY}/${REPOSITORY}:${TAG1}
    ports:
      - "80:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  runserver:
    build:
      context: ./runserver
      dockerfile: Dockerfile
    image: ${REGISTRY}/${REPOSITORY}:${TAG2}
    ports:
      - "9090:8080"
