version: "3.8"

services:
  mainserver:
    build:
      context: ./idemainserver
      dockerfile: Dockerfile
    image: ${REGISTRY}/${REPOSITORY}:${TAG1}
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
  runserver:
    build:
      context: ./runserver
      dockerfile: Dockerfile
    image: ${REGISTRY}/${REPOSITORY}:${TAG2}
    ports:
      - "9090:8080"
