spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1243286157-8o57m0ikrgv821bv0d6ajfqtn83vbdcq.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email

          naver:
            client-id: KOtfSrf9kM4ibXyiTiAq
            client-secret: NFRdR2tOhL
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 3d5cf697b49c6f1b80ba5fd3ea80e62c
            client-secret: fxQwj7mqOtZoVh1IXPYswWeJZLIAPt39
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao  #http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id